/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file for additional
 * information regarding copyright ownership.
 */
package org.apache.roller.weblogger.business.pulse;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import org.apache.roller.weblogger.pojos.WeblogEntryComment;

/**
 * Method 1: TF-IDF keyword clustering (fully classical, no LLM).
 *
 * Computes TF-IDF scores per comment, clusters comments by shared top terms,
 * labels each cluster from its most prominent keywords, and picks
 * representative comments (closest to cluster centroid by keyword overlap).
 *
 * Recap is generated by summarizing cluster sizes and labels.
 */
public class TfIdfBreakdownStrategy implements BreakdownStrategy {

    private static final Set<String> STOP_WORDS = new HashSet<>(Arrays.asList(
            "the", "a", "an", "and", "or", "but", "in", "on", "at", "to",
            "for", "of", "with", "by", "from", "is", "it", "this", "that",
            "was", "are", "were", "be", "been", "being", "have", "has", "had",
            "do", "does", "did", "will", "would", "could", "should", "may",
            "might", "shall", "can", "need", "not", "so", "no", "nor",
            "as", "if", "then", "than", "too", "very", "just", "about",
            "above", "after", "again", "all", "also", "am", "any", "because",
            "before", "between", "both", "each", "few", "get", "got", "here",
            "her", "him", "his", "how", "its", "into", "like", "more", "most",
            "much", "my", "new", "now", "only", "other", "our", "out", "over",
            "own", "same", "she", "some", "still", "such", "take", "their",
            "them", "these", "they", "those", "through", "under", "up", "us",
            "way", "we", "well", "what", "when", "where", "which", "while",
            "who", "whom", "why", "you", "your", "one", "two", "even",
            "back", "make", "many", "there", "think", "know", "said", "says",
            "say", "going", "really", "right", "don", "doesn", "didn", "won",
            "isn", "http", "https", "www", "com"
    ));

    private static final int MAX_THEMES = 5;
    private static final int REPS_PER_THEME = 2;

    @Override
    public String getName() { return "tfidf"; }

    @Override
    public String getDescription() {
        return "TF-IDF keyword clustering — fully classical, no LLM";
    }

    @Override
    public ConversationBreakdown analyze(CommentData data) {
        List<WeblogEntryComment> comments = data.getComments();

        if (comments.isEmpty()) {
            return new ConversationBreakdown(new ArrayList<>(),
                    "No comments to analyze.", getName());
        }

        // 1. Tokenize each comment
        List<List<String>> tokenized = new ArrayList<>();
        List<String> rawTexts = new ArrayList<>();
        for (WeblogEntryComment c : comments) {
            String text = stripHtml(c.getContent());
            rawTexts.add(text);
            tokenized.add(tokenize(text));
        }

        // 2. Compute IDF (inverse document frequency)
        Map<String, Integer> docFreq = new HashMap<>();
        for (List<String> tokens : tokenized) {
            Set<String> unique = new HashSet<>(tokens);
            for (String word : unique) {
                docFreq.merge(word, 1, Integer::sum);
            }
        }

        int totalDocs = tokenized.size();
        Map<String, Double> idf = new HashMap<>();
        for (Map.Entry<String, Integer> entry : docFreq.entrySet()) {
            idf.put(entry.getKey(),
                    Math.log((double) totalDocs / (1 + entry.getValue())));
        }

        // 3. Compute TF-IDF vectors per comment
        List<Map<String, Double>> tfidfVectors = new ArrayList<>();
        for (List<String> tokens : tokenized) {
            Map<String, Integer> tf = new HashMap<>();
            for (String word : tokens) {
                tf.merge(word, 1, Integer::sum);
            }
            Map<String, Double> vector = new HashMap<>();
            for (Map.Entry<String, Integer> entry : tf.entrySet()) {
                double tfidfScore = entry.getValue()
                        * idf.getOrDefault(entry.getKey(), 0.0);
                if (tfidfScore > 0) {
                    vector.put(entry.getKey(), tfidfScore);
                }
            }
            tfidfVectors.add(vector);
        }

        // 4. Get global top keywords
        Map<String, Double> globalScores = new HashMap<>();
        for (Map<String, Double> vector : tfidfVectors) {
            for (Map.Entry<String, Double> entry : vector.entrySet()) {
                globalScores.merge(entry.getKey(), entry.getValue(), Double::sum);
            }
        }

        List<String> topKeywords = globalScores.entrySet().stream()
                .sorted(Map.Entry.<String, Double>comparingByValue(Comparator.reverseOrder()))
                .limit(MAX_THEMES * 3)
                .map(Map.Entry::getKey)
                .collect(Collectors.toList());

        // 5. Simple clustering: assign each comment to the keyword it scores highest on
        Map<String, List<Integer>> clusters = new HashMap<>();
        for (String kw : topKeywords) {
            clusters.put(kw, new ArrayList<>());
        }

        for (int i = 0; i < tfidfVectors.size(); i++) {
            Map<String, Double> vector = tfidfVectors.get(i);
            String bestKeyword = null;
            double bestScore = 0;
            for (String kw : topKeywords) {
                double score = vector.getOrDefault(kw, 0.0);
                if (score > bestScore) {
                    bestScore = score;
                    bestKeyword = kw;
                }
            }
            if (bestKeyword != null && bestScore > 0) {
                clusters.get(bestKeyword).add(i);
            }
        }

        // 6. Merge small clusters and build themes
        List<ConversationTheme> themes = new ArrayList<>();
        Set<String> usedClusters = new HashSet<>();

        List<Map.Entry<String, List<Integer>>> sortedClusters = clusters.entrySet().stream()
                .filter(e -> !e.getValue().isEmpty())
                .sorted((a, b) -> Integer.compare(b.getValue().size(), a.getValue().size()))
                .collect(Collectors.toList());

        for (Map.Entry<String, List<Integer>> entry : sortedClusters) {
            if (themes.size() >= MAX_THEMES) break;
            if (usedClusters.contains(entry.getKey())) continue;

            String primaryKeyword = entry.getKey();
            List<Integer> memberIndices = entry.getValue();
            usedClusters.add(primaryKeyword);

            // Collect co-occurring keywords for this cluster
            Map<String, Integer> coKeywords = new HashMap<>();
            for (int idx : memberIndices) {
                for (String word : tokenized.get(idx)) {
                    if (!word.equals(primaryKeyword)) {
                        coKeywords.merge(word, 1, Integer::sum);
                    }
                }
            }
            List<String> clusterKeywords = new ArrayList<>();
            clusterKeywords.add(primaryKeyword);
            coKeywords.entrySet().stream()
                    .sorted(Map.Entry.<String, Integer>comparingByValue(Comparator.reverseOrder()))
                    .limit(3)
                    .forEach(e -> clusterKeywords.add(e.getKey()));

            // Label: capitalize primary keyword
            String label = capitalize(primaryKeyword);

            // Representative comments: pick top REPS_PER_THEME by TF-IDF score for this keyword
            List<String> reps = memberIndices.stream()
                    .sorted((a, b) -> Double.compare(
                            tfidfVectors.get(b).getOrDefault(primaryKeyword, 0.0),
                            tfidfVectors.get(a).getOrDefault(primaryKeyword, 0.0)))
                    .limit(REPS_PER_THEME)
                    .map(idx -> truncate(rawTexts.get(idx), 200))
                    .collect(Collectors.toList());

            themes.add(new ConversationTheme(label, clusterKeywords, reps, memberIndices.size()));
        }

        // 7. Generate recap
        String recap = generateRecap(data, themes);

        return new ConversationBreakdown(themes, recap, getName());
    }

    private String generateRecap(CommentData data, List<ConversationTheme> themes) {
        StringBuilder sb = new StringBuilder();
        sb.append("This entry has ").append(data.getCommentCount())
          .append(" comment(s). ");

        if (themes.isEmpty()) {
            sb.append("No clear discussion themes emerged.");
            return sb.toString();
        }

        sb.append("The discussion revolves around ")
          .append(themes.size()).append(" main topic(s): ");

        for (int i = 0; i < themes.size(); i++) {
            ConversationTheme theme = themes.get(i);
            if (i > 0) sb.append(", ");
            sb.append("\"").append(theme.getLabel()).append("\"")
              .append(" (").append(theme.getCommentCount()).append(" comments)");
        }
        sb.append(".");

        return sb.toString();
    }

    private List<String> tokenize(String text) {
        if (text == null || text.isEmpty()) return new ArrayList<>();
        String[] words = text.toLowerCase().split("[^a-zA-Z0-9]+");
        List<String> result = new ArrayList<>();
        for (String word : words) {
            if (word.length() >= 3 && !STOP_WORDS.contains(word)) {
                result.add(word);
            }
        }
        return result;
    }

    private String stripHtml(String text) {
        if (text == null) return "";
        return text.replaceAll("<[^>]+>", " ").replaceAll("&\\w+;", " ").trim();
    }

    private String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return s.substring(0, 1).toUpperCase() + s.substring(1);
    }

    private String truncate(String text, int maxLen) {
        if (text == null) return "";
        if (text.length() <= maxLen) return text;
        return text.substring(0, maxLen) + "...";
    }
}
