#!/usr/bin/env python3
"""
UML Class Diagram Generator for Apache Roller

Parses Java source files and generates PlantUML class diagrams automatically.
This script scans the given source directories, extracts class/interface
definitions, fields, methods, and relationships, and outputs a .puml file.

Usage:
    python3 generate_uml.py [--scope full|pipeline|stars] [--output FILE]
"""

import os
import re
import sys
import argparse
from datetime import datetime


def parse_java_file(filepath):
    """Parse a Java file and extract class/interface information."""
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()

    result = {
        'package': '',
        'name': '',
        'type': 'class',  # class, interface, enum, abstract
        'fields': [],
        'methods': [],
        'implements': [],
        'extends': None,
        'filepath': filepath,
    }

    # Package
    pkg_match = re.search(r'package\s+([\w.]+)\s*;', content)
    if pkg_match:
        result['package'] = pkg_match.group(1)

    # Strip block comments and line comments before parsing declaration
    code_only = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
    code_only = re.sub(r'//.*', '', code_only)

    # Class/Interface declaration (handles final, static modifiers)
    decl = re.search(
        r'(public\s+)?(?:(?:abstract|final|static)\s+)*'
        r'(class|interface|enum)\s+(\w+)'
        r'(?:\s+extends\s+([\w.]+))?'
        r'(?:\s+implements\s+([\w.,\s]+))?',
        code_only
    )
    if not decl:
        return None

    # Check if abstract appears in modifiers before the class keyword
    modifiers_before = content[:decl.start(2)] if decl.start(2) > 0 else ''
    if 'abstract' in modifiers_before.split('\n')[-1]:
        result['type'] = 'abstract'
    else:
        result['type'] = decl.group(2)

    result['name'] = decl.group(3)

    if decl.group(4):
        result['extends'] = decl.group(4).split('.')[-1]

    if decl.group(5):
        result['implements'] = [
            i.strip().split('.')[-1]
            for i in decl.group(5).split(',')
        ]

    # Fields (private/protected/public)
    for m in re.finditer(
        r'(?:private|protected|public)\s+'
        r'(?:static\s+)?(?:final\s+)?'
        r'([\w<>\[\]?,\s]+?)\s+(\w+)\s*[;=]', content
    ):
        ftype = m.group(1).strip()
        fname = m.group(2).strip()
        # Skip constants (ALL_CAPS) and serialVersionUID
        if fname.isupper() or fname == 'serialVersionUID':
            continue
        result['fields'].append((fname, ftype))

    # Methods (public/protected)
    for m in re.finditer(
        r'(?:public|protected)\s+'
        r'(?:static\s+)?(?:abstract\s+)?'
        r'([\w<>\[\]?,\s]+?)\s+(\w+)\s*\(([^)]*)\)',
        content
    ):
        rtype = m.group(1).strip()
        mname = m.group(2).strip()
        params = m.group(3).strip()
        # Skip getters/setters/constructors/toString/equals/hashCode
        if (mname.startswith('get') or mname.startswith('set')
                or mname.startswith('is')
                or mname in ('toString', 'equals', 'hashCode',
                             result['name'])):
            continue
        # Simplify params
        if params:
            simplified = []
            for p in params.split(','):
                p = p.strip()
                parts = p.split()
                if len(parts) >= 2:
                    simplified.append(parts[-2].split('.')[-1]
                                      + ' ' + parts[-1])
            params = ', '.join(simplified)
        result['methods'].append((mname, rtype, params))

    return result


def generate_puml(classes, title, scope_desc):
    """Generate PlantUML content from parsed class data."""
    lines = ['@startuml']
    lines.append('skinparam classAttributeIconSize 0')
    lines.append('skinparam linetype ortho')
    lines.append('skinparam nodesep 60')
    lines.append('skinparam ranksep 40')
    lines.append('')
    lines.append(f"' {title}")
    lines.append(f"' Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"' Scope: {scope_desc}")
    lines.append(f"' Generated by: generate_uml.py")
    lines.append('')

    # Group by package
    packages = {}
    for cls in classes:
        pkg = cls['package']
        if pkg not in packages:
            packages[pkg] = []
        packages[pkg].append(cls)

    # Track all class names for relationship filtering
    all_names = {cls['name'] for cls in classes}

    for pkg in sorted(packages.keys()):
        short_pkg = pkg.split('.')[-1] if '.' in pkg else pkg
        lines.append(f'package "{pkg}" <<{short_pkg}>> {{')

        for cls in sorted(packages[pkg], key=lambda c: c['name']):
            # Determine class type
            if cls['type'] == 'interface':
                lines.append(f"  interface {cls['name']} {{")
            elif cls['type'] == 'abstract':
                lines.append(f"  abstract class {cls['name']} {{")
            elif cls['type'] == 'enum':
                lines.append(f"  enum {cls['name']} {{")
            else:
                lines.append(f"  class {cls['name']} {{")

            # Fields
            for fname, ftype in cls['fields'][:10]:  # limit fields
                lines.append(f"    -{fname} : {ftype}")

            # Methods
            for mname, rtype, params in cls['methods'][:8]:  # limit methods
                lines.append(f"    +{mname}({params}) : {rtype}")

            lines.append('  }')
            lines.append('')

        lines.append('}')
        lines.append('')

    # Relationships
    lines.append("' Relationships")
    for cls in classes:
        if cls['extends'] and cls['extends'] in all_names:
            lines.append(f"{cls['extends']} <|-- {cls['name']}")

        for iface in cls['implements']:
            if iface in all_names:
                lines.append(f"{iface} <|.. {cls['name']}")

        # Composition/association from field types
        for fname, ftype in cls['fields']:
            # Extract simple type name from generics
            for tname in re.findall(r'[A-Z]\w+', ftype):
                if tname in all_names and tname != cls['name']:
                    lines.append(f'{cls["name"]} --> {tname} : {fname}')

    lines.append('')
    lines.append('@enduml')
    return '\n'.join(lines)


def find_java_files(base_dir, packages=None):
    """Find all Java files, optionally filtered by package patterns."""
    java_files = []
    for root, dirs, files in os.walk(base_dir):
        for f in files:
            if f.endswith('.java') and not f.startswith('package-info'):
                filepath = os.path.join(root, f)
                if packages:
                    # Check if any package pattern matches
                    for pkg in packages:
                        if pkg in filepath.replace(os.sep, '.'):
                            java_files.append(filepath)
                            break
                else:
                    java_files.append(filepath)
    return java_files


def main():
    parser = argparse.ArgumentParser(
        description='Generate PlantUML class diagrams from Java source')
    parser.add_argument('--scope', default='pipeline',
                        choices=['full', 'pipeline', 'stars', 'task2',
                                 'pulse-before', 'pulse-after'],
                        help='Scope of diagram to generate')
    parser.add_argument('--output', default=None,
                        help='Output file path')
    parser.add_argument('--source', default=None,
                        help='Source directory')
    args = parser.parse_args()

    # Determine source directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    source_dir = args.source or os.path.join(
        project_root, 'app', 'src', 'main', 'java')

    if not os.path.isdir(source_dir):
        print(f"Error: source directory not found: {source_dir}",
              file=sys.stderr)
        sys.exit(1)

    # Define scope
    if args.scope == 'pipeline' or args.scope == 'task2':
        packages = ['business.pipeline', 'editor.EntryEdit',
                     'plugins.entry']
        title = 'Task 2 - Transforming Feeds Pipeline'
        scope_desc = 'Entry processing pipeline classes'
        default_output = 'task2_transforming_feeds.puml'
    elif args.scope == 'stars':
        packages = ['pojos.UserEntryStar', 'pojos.UserWeblogStar',
                     'business.StarManager', 'business.jpa.JPAStarManager',
                     'struts2.core.Star', 'struts2.core.Starred',
                     'struts2.core.Trending', 'pagers.StarredEntries']
        title = 'Task 1 - User Highlights (Stars & Trending)'
        scope_desc = 'Star/favourite and trending classes'
        default_output = 'task1_user_highlights.puml'
    elif args.scope == 'pulse-before':
        packages = ['pojos.WeblogEntryComment', 'pojos.CommentSearchCriteria',
                     'business.WeblogEntryManager',
                     'business.jpa.JPAWeblogEntryManager',
                     'struts2.editor.Comments', 'struts2.editor.CommentsBean']
        title = 'Task 6 - Community Pulse Dashboard (BEFORE)'
        scope_desc = 'Existing comment infrastructure before Community Pulse'
        default_output = 'task6_community_pulse_before.puml'
    elif args.scope == 'pulse-after':
        packages = ['pojos.WeblogEntryComment', 'pojos.CommentSearchCriteria',
                     'business.WeblogEntryManager',
                     'business.jpa.JPAWeblogEntryManager',
                     'struts2.editor.Comments', 'struts2.editor.CommentsBean',
                     'business.pulse']
        title = 'Task 6 - Community Pulse Dashboard (AFTER)'
        scope_desc = 'Comment infrastructure with Community Pulse analytics'
        default_output = 'task6_community_pulse_after.puml'
    else:  # full
        packages = None
        title = 'Full Domain Model'
        scope_desc = 'All classes in the weblogger package'
        default_output = 'full_domain_model_updated.puml'

    output = args.output or os.path.join(script_dir, default_output)

    # Find and parse files
    java_files = find_java_files(source_dir, packages)
    print(f"Found {len(java_files)} Java files for scope '{args.scope}'")

    classes = []
    for jf in java_files:
        parsed = parse_java_file(jf)
        if parsed:
            classes.append(parsed)

    print(f"Parsed {len(classes)} classes/interfaces")

    # Generate PlantUML
    puml = generate_puml(classes, title, scope_desc)

    with open(output, 'w', encoding='utf-8') as f:
        f.write(puml)

    print(f"Generated: {output}")


if __name__ == '__main__':
    main()
